[package]
name = "udoc-rs"
version = "0.1.1"
edition = "2021"

[dependencies]
slice-reader = {version = "0.1.1", git = "https://github.com/leddoo/slice-reader"}

[lib]
name = "udoc"
path = "src/lib.rs"
